# @package _global_
defaults:
  - /tokenizer: nltk

model:
  news_encoder:
    _target_: src.models.news_encoders.tanr.TANRNewsEncoder
    word_embedding_dim: 300
    use_pretrained_embeddings: true
    freeze_pretrained_embeddings: false
    window_size: 3
    num_filters: 300
