defaults:
  - _self_

  # optional local config for machine specific settings
  - optional local: default

hydra:
  job:
    chdir: true

seed: 704
epochs: 5
batch_size: 64
negative_sampling_ratio: 4
num_words_title: 20
num_words_abstract: 50
history_length: 50
num_batches_show_loss: 100
tqdm_disable: false
mind_variant: "200k"
use_history_mask: true
num_workers: 4
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
