# @package _global_
defaults:
  - /tokenizer: bert

model:
  _target_: models.BERT_NRMS.BERT_NRMS
  pretrained_model_name: bert-base-uncased
  bert_pooling_method: attention
  num_hidden_layers: 8

features:
  - title
