# @package _global_
defaults:
  - /model/news_encoder: bert
  - /model/user_encoder: multi_interest
  - /model/click_predictor: multi_interest
  - /model/loss:
    - prediction
    - interest_disagreement

model:
  news_encoder:
    finetune_n_last_layers: -1

features:
  - title

optimizer:
  lr: 2e-5
